Update to new upstream version & use Erlang 24.1.7 for all targets
With the precedent Erlang dependency for Fedora, i.e. `>= 23, < 25`, build
for Fedora 35 failed with error:
```
==> rel (generate)
ERROR: Unable to generate spec: read file info /usr/lib64/erlang/lib/dialyzer-4.4.4/doc/chunks failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /builddir/build/BUILD/apache-couchdb-3.2.2/rel: rebar_abort
make: *** [Makefile:381: release] Error 1
```
I think it's due to a change in Erlang between version 24.1.7 and the current most
recent, version 24.3.3.
On Fedora 35 we could have used the official Erlang 24.1.4 which is still
available but that doesn't work for Fedora 36, so let's just use our own build
Erlang 24.1.7 for Epel and both Fedora (available in adrienverge copr).