Update to CouchDB 3.4.1 + QuickJS + Erlang 26 + other changes
Changes :

- Update to CouchDB 3.4.1.

- Use Erlang 26 (CouchDB 3.4.1 requires ≥ 25, ≤ 27). This version is
  officially packaged on all releases (EPEL 9, Fedora 40 and Fedora 41)
  so we don't need our private erlang-24.3.4.15 anymore.

- Drop SpiderMonkey and use QuickJS, as recommended by CouchDB 3.4.1
  release notes. QuickJS was already packaged on a COPR, thanks to
  https://copr.fedorainfracloud.org/coprs/ycollet/audinux/
  Anyway mosjz91 wasn't packaged in latest Fedora versions, and our
  custom RPM fails to build on Fedora ≥ 41 and EPEL 9.

- On Fedora only, create and depend on our custom package
  erlang-doc-fix-missing-chunks, that creates 3 missing directories from
  erlang-doc. Otherwise building fails during one of the last steps:

      ==> rel (generate)
      ERROR: Unable to generate spec: read file info /usr/lib64/erlang/lib/erl_interface-5.5.1/doc/chunks failed
      ERROR: Unexpected error: rebar_abort
      ERROR: generate failed while processing /builddir/build/BUILD/couchdb-3.4.1-build/apache-couchdb-3.4.1/rel: rebar_abort
      make: *** [Makefile:408: release] Error 1

I could verify that with the new version, `ps` shows a lot of processes
`…/couch_quickjs-3.4.1/priv/couchjs_mainjs` running.

I tested on a Rocky Linux 9 machine, from a state with
`couchdb-3.3.3-2.el9` installed + some data in database, upgrading to
`couchdb-3.4.1-1.el9` seems to work smoothly and data is accessible,
users stay logged in.

Rollbacking the server to version 3.3.3 also worked: after a restart,
logs correctly end up with `rexi_server : cluster stable`, and a
previously-logged in user stays logged in.